services:
  tracker:
    build: ./tracker
    image: open-quran-tracker:1.1
    container_name: open-quran-tracker
    ports:
      - "8083:8083"
    networks:
      - webtorrent-net

  seed-server:
    build: ./seed-server
    image: open-quran-seeder:1.1
    container_name: open-quran-seeder
    volumes:
      - ./seed-server/seed.mjs:/app/seed.mjs
      - seed_downloads:/app/downloads
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - webtorrent-net
    depends_on:
      - tracker

networks:
  webtorrent-net:
    driver: bridge

volumes:
  seed_downloads:
